#!/bin/sh

CONFDIR=/home/samb/camp/catalogs/strap/config
TAGDIR=/home/samb/camp/interchange/code/template_tag/strap

die() {
	echo $1
	exit 1
}

cd $CONFDIR || die "Cannot find $CONFDIR to change to.";

if [ "x`whoami`" = xroot ]
then
	ISROOT=1
else
	ISROOT=0
fi

if test -d $TAGDIR
then
	HASTAGDIR=1
else 
	mkdir -p /home/samb/camp/interchange/code/template_tag/strap \
		|| die "Cannot make $TAGDIR"
fi

for f in *.tag *.am
do
	if test -f /home/samb/camp/interchange/usertag/$f
	then
		echo "$f appears to be in global usertag/ directory, skipping."
	else
		cp $f $TAGDIR || die "Cannot copy $f to $TAGDIR: $!"
	fi
done

for f in *.filter
do
	if test -f /home/samb/camp/interchange/filter/$f
	then
		echo "$f appears to be in global filter/ directory, skipping."
	else
		cp $f $TAGDIR || die "Cannot copy $f to $TAGDIR: $!"
	fi
done
