#!/bin/sh

PERMTYPE=`echo  | sed -e 's/\(.\).*/\1/' | tr a-z A-Z`

if [ "x`whoami`" = xroot ]
then
	if test "x$PERMTYPE" = x -o "x$PERMTYPE" = xM
	then
		CATUSER=samb
		CATGROUP=
	elif test "x$PERMTYPE" = xG
	then
		CATUSER=samb
		CATGROUP=
	else
		CATUSER=samb
		CATGROUP=users
	fi
fi

if test "x$PERMTYPE" = x -o "x$PERMTYPE" = xM -o "x$PERMTYPE" = xG
then
	DMODE=2770
	FMODE=660
else
	DMODE=700
	FMODE=600
fi

# Link the image directory always
ln -s /home/samb/camp/htdocs/strap/images /home/samb/camp/catalogs/strap

# Link the server directory to 'i'
ln -s /home/samb/camp/interchange /home/samb/camp/catalogs/strap/i

# Make run directory to store run files.
if test -n ''
then
	RUNDIR=''
	mkdir -p     $RUNDIR
	if test -n "$CATUSER"
	then
		[ -n "$CATUSER"  ] && chown $CATUSER  $RUNDIR
		[ -n "$CATGROUP" ] && chgrp $CATGROUP $RUNDIR
	fi
	chmod $DMODE $RUNDIR
else
	RUNDIR='/home/samb/camp/catalogs/strap/run'
	mkdir -p     $RUNDIR
	if test -n "$CATUSER"
	then
		[ -n "$CATUSER"  ] && chown $CATUSER  $RUNDIR
		[ -n "$CATGROUP" ] && chgrp $CATGROUP $RUNDIR
	fi
	chmod $DMODE $RUNDIR
fi

# Make log directories to store logs.
if test -n ''
then 
	LOGDIR=''
	mkdir -p     $LOGDIR/logs
	mkdir -p     $LOGDIR/orders
	touch        $LOGDIR/logs/error.log
	ln    -s     $LOGDIR/error.log /home/samb/camp/catalogs/strap
	ln    -s     $LOGDIR/logs      /home/samb/camp/catalogs/strap
	ln    -s     $LOGDIR/orders    /home/samb/camp/catalogs/strap
	chmod $DMODE $LOGDIR/logs
	chmod $DMODE $LOGDIR/orders
	touch        $LOGDIR/logs/error.log
	if test -n "$CATUSER"
	then
		[ -n "$CATUSER"  ] && chown $CATUSER  $LOGDIR/error.log
		[ -n "$CATGROUP" ] && chgrp $CATGROUP $LOGDIR/error.log
	fi
else
	LOGDIR='/home/samb/camp/catalogs/strap'
	mkdir -p     $LOGDIR/orders
	mkdir -p     $LOGDIR/logs
	chmod $DMODE $LOGDIR/logs
	chmod $DMODE $LOGDIR/orders
	touch        $LOGDIR/logs/error.log
	if test -n "$CATUSER"
	then
		[ -n "$CATUSER"  ] && chown $CATUSER  $LOGDIR/logs/error.log
		[ -n "$CATGROUP" ] && chgrp $CATGROUP $LOGDIR/logs/error.log
	fi
fi

chmod $FMODE $LOGDIR/logs/error.log
chmod $FMODE /home/samb/camp/catalogs/strap/catalog.cfg


## Create Bcrypt Pepper
perl -e '@c=("A".."Z","a".."z",0..9);$p.=$c[rand(scalar @c)] for 1..32; print $p' > /home/samb/camp/catalogs/strap/variables/BCRYPT_PEPPER

# Make cache directories to store tmps.
if test -n ''
then 
	CACHEDIR=''
	mkdir -p $CACHEDIR/session
	ln    -s $CACHEDIR/session /home/samb/camp/catalogs/strap
	mkdir -p $CACHEDIR/tmp
	ln    -s $CACHEDIR/tmp     /home/samb/camp/catalogs/strap
else
	CACHEDIR='/home/samb/camp/catalogs/strap'
	mkdir -p     $CACHEDIR/session
	mkdir -p     $CACHEDIR/tmp
	chmod $DMODE $CACHEDIR/session
	chmod $DMODE $CACHEDIR/tmp
fi

# Fix directory ownership if running as root
if test -n "$CATUSER"
then
	for i in $LOGDIR/logs $LOGDIR/orders $CACHEDIR/session $CACHEDIR/tmp
	do
		[ -n "$CATUSER"  ] && chown $CATUSER $i
		[ -n "$CATGROUP" ] && chgrp $CATGROUP $i
	done
fi

# Remove .git directory from installed catalog, if present (it is copied during makecat, if the template was cloned from Git)
if test -d "/home/samb/camp/catalogs/strap/.git"
then
	rm -rf /home/samb/camp/catalogs/strap/.git
fi
